### ISSUE TITLE
Falta validación en el campo de vencimiento

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-hueda-tula-cuozzo#17]
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-hueda-tula-cuozzo/assets/8345007/57f0563c-53b0-4a95-8ae5-5833f400f9ec)

**Comment by 2203601** [comment]
Profe, a nosotras esa parte la tenemos como " type = month " entonces a nosotras no nos aparece la opción para escribir.
